AuthenticateUserFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: authenticate_user/
    Handler: app.lambda_handler
    Runtime: python3.8
    Events:
      AuthenticateUser:
        Type: Api
        Properties:
          Path: /AuthenticateUser
          Method: post
