AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CHP Lambda Function Backend
Globals:
  Function:
    Timeout: 30
Resources:
  AddRoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_round/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        AddRound:
          Type: Api
          Properties:
            Path: /AddRound
            Method: post
  ScheduleDatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: schedule_dates/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        ScheduleDates:
          Type: Api
          Properties:
            Path: /ScheduleDates
            Method: post
Outputs:
  AddRoundApi:
    Description: API Gateway AddRound for CHP
    Value: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/AddRound
  AddRoundFunction:
    Description: AddRound Lambda Function ARN
    Value: AddRoundFunction.Arn
  AddRoundRequestIamRole:
    Description: Implicit IAM Role created for AddRound Request function
    Value: AddRoundFunctionRole.Arn
  ScheduleDatesApi:
    Description: API Gateway ScheduleDates for CHP
    Value: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ScheduleDates
  ScheduleDatesFunction:
    Description: ScheduleDates Lambda Function ARN
    Value: ScheduleDatesFunction.Arn
  ScheduleDatesRequestIamRole:
    Description: Implicit IAM Role created for ScheduleDates Request function
    Value: ScheduleDatesFunctionRole.Arn
